In [2]:
import numpy as np

$$
\mathbf{f} = 
\begin{bmatrix} f_{150.0,\:152.5} \\ f_{152.5,\:155.0} \\ f_{155.0,\:157.5} \\
 f_{157.5,\:160.0} \\ f_{160.0,\:162.5} \\ \vdots \end{bmatrix}
$$



$$ \mathbf{g}_\mathbf{p}  = \begin{bmatrix} g_{150.0,\:152.5} \\ g_{152.5,\:155.0} \\ g_{155.0,\:157.5} \\ g_{157.5,\:160.0} \\ g_{160.0,\:162.5} \\ \vdots 
\end{bmatrix} $$



La base es un conjunto de n vectores que :

No son combinaciones lineales entre sí (linealmente independientes)

Abarquen el espacio 

El espacio es entonces de n dimensiones

¿Qué significa que un vector $\mathbf{b_3}$ sea linealmente independiente de los vectores $\mathbf{b_1}$? 
  y $\mathbf{b_2}$ ? Seleccione todas las respuestas correctas.


-  $ \mathbf{b_3} = \mathbf{b_1} + \mathbf{b_2} $


- $ \mathbf{b_3}$ no se encuentra en el plano abarcado por $\mathbf{b_1} y \mathbf{b_2}$  
    - Correcto  
        Esta es una forma geométrica de entender la independencia lineal.  

- $ \mathbf{b_3} \neq a_1\mathbf{b_1} + a_2\mathbf{b_2} $, for any $a_{1}$ or $a_{2}$ 
    - Correcto  
        Esta es una forma algebraica de entender la independencia lineal.

- $\mathbf{b_3} = a_1\mathbf{b_1} + a_2\mathbf{b_2}$ para algunos$a_{1}$ or  $a_{2}$ 


Completar el cálculo ante el profesor: dado 

$A_1 = \begin{bmatrix} 0 & 1 \\ -1 & 0\end{bmatrix}$   
y  
$A_2 = \begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix}$   
qué es  
$A_1\cdot A_2  =  \begin{bmatrix} 0 & 1 \\ -1 & 0\end{bmatrix} \begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix}$ 


In [2]:
np.dot(np.array([[0,1],[-1,0]]), 
       np.array([[1,1],[0,1]]))

array([[ 0,  1],
       [-1, -1]])

# Composición o combinación de transformaciones matriciales

In [3]:
a1 = np.array([[0,1],
               [-1,0]])

In [4]:
a2 = np.array([[-1,0],
               [0,1]])

In [5]:
a3 = np.array([[2,0],
               [0,2]])

## Propiedad Asociativa

In [6]:
a1.dot(np.dot(a2,a3))

array([[0, 2],
       [2, 0]])

In [7]:
a3.dot(np.dot(a1,a2))

array([[0, 2],
       [2, 0]])

In [8]:
np.dot(a1,a2).dot(a3)

array([[0, 2],
       [2, 0]])

In [9]:
np.dot(a2,a1).dot(a3)

array([[ 0, -2],
       [-2,  0]])

In [10]:
(a1 * 3 ).dot(a2)

array([[0, 3],
       [3, 0]])

In [11]:
(a1).dot(a2 * 3 )

array([[0, 3],
       [3, 0]])

In [12]:
(a2).dot(a1 * 3 )

array([[ 0, -3],
       [-3,  0]])

In [13]:
(a2*3).dot(a1)

array([[ 0, -3],
       [-3,  0]])

Conclución
----------

Se cumple la Propiedad Asociativa

## Propiedad Conmutativa

In [14]:
a1.dot(a2)

array([[0, 1],
       [1, 0]])

In [15]:
a2.dot(a1)

array([[ 0, -1],
       [-1,  0]])

Conclución
----------

**NO** Se cumple la Propiedad Conmutativa

# Matriz Inversa 

In [16]:
# matriz inversa de a1
print(a1)
a1_inv = np.linalg.inv(a1)
print(a1_inv)

[[ 0  1]
 [-1  0]]
[[-0. -1.]
 [ 1.  0.]]


In [17]:
a1_inv[0]

array([-0., -1.])

In [18]:
# el resultado del producto punto o matricial entre su matriz i su inversa 
# da como resultado una matriz identidad con las dimenciones de la matriz

a1.dot(a1_inv)

array([[1., 0.],
       [0., 1.]])

# Sistemas de ecuaciones lineales

Una de las principales aplicaciones del [Álgebra lineal](https://es.wikipedia.org/wiki/%C3%81lgebra_lineal) consiste en resolver problemas de sistemas de ecuaciones lineales.

Una [ecuación lineal](https://es.wikipedia.org/wiki/Ecuaci%C3%B3n_de_primer_grado) es una ecuación que solo involucra sumas y restas de una variable o mas variables a la primera potencia. Es la ecuación de la línea recta.Cuando nuestro problema esta representado por más de una [ecuación lineal](https://es.wikipedia.org/wiki/Ecuaci%C3%B3n_de_primer_grado), hablamos de un [sistema de ecuaciones lineales](https://es.wikipedia.org/wiki/Sistema_de_ecuaciones_lineales). Por ejemplo, podríamos tener un sistema de dos ecuaciones con dos incógnitas como el siguiente:

$$ x - 2y = 1$$ 
$$3x + 2y = 11$$

La idea es encontrar el valor de $x$ e $y$ que resuelva ambas ecuaciones. Una forma en que podemos hacer esto, puede ser representando graficamente ambas rectas y buscar los puntos en que las rectas se cruzan. 

En [Python](https://python.org/) esto se puede hacer en forma muy sencilla con la ayuda de [matplotlib](https://matplotlib.org/).

Por ejemplo, para resolver este sistema de 3 ecuaciones y 3 incógnitas.

$$ 3x + 2y + 3z = 11$$
$$ 2x + 5y + 2z = 11$$
$$ 6x - 3y + z = 5$$

In [19]:
# Creando matriz de coeficientes
A = np.array([[3, 2, 3],
              [2, 5, 2],
              [6, -3, 1]])
A

array([[ 3,  2,  3],
       [ 2,  5,  2],
       [ 6, -3,  1]])

In [20]:
# Creando matriz de resultados
b = np.array([11, 5, 5])
b

array([11,  5,  5])

In [21]:
# Resolviendo sistema de ecuaciones
x = np.linalg.solve(A, b)
x

array([-0.2       , -0.63636364,  4.29090909])

In [22]:
# Comprobando la solucion
A @ x == b

array([ True,  True,  True])

In [23]:
inv_A = np.linalg.inv(A)
inv_A

array([[-2.00000000e-01,  2.00000000e-01,  2.00000000e-01],
       [-1.81818182e-01,  2.72727273e-01,  1.63449501e-17],
       [ 6.54545455e-01, -3.81818182e-01, -2.00000000e-01]])

In [24]:
A.dot(inv_A)

array([[ 1.00000000e+00, -1.66533454e-16, -1.38777878e-16],
       [-2.22044605e-16,  1.00000000e+00, -5.55111512e-17],
       [-1.11022302e-16, -5.55111512e-17,  1.00000000e+00]])

In [25]:
x1 = inv_A.dot(b)

In [26]:
x1

array([-0.2       , -0.63636364,  4.29090909])

In [27]:
(A @ x1).astype(np.int8) == b 

array([False, False, False])

In [28]:
(A @ x1).astype(np.int64)

array([10,  4,  4])

In [29]:
b

array([11,  5,  5])

Para la matriz $A = \begin{bmatrix} 1 & 1 & 3 \\ 1 & 2 & 4 \\ 1 & 1 & 2\end{bmatrix}$  


calcula la nueva matriz A'  
que tiene las mismas entradas que A, sin embargo la segunda fila de A' 
es la segunda de la fila A menos la primera fila de A, y la tercera fila de A' 
es la tercera fila de A menos la primera fila de A.

$A^{`} = \begin{bmatrix} 1 & 1 & 3 \\ 0 & 1 & 1 \\ 0 & 0 & -1\end{bmatrix}$

In [30]:


A1 = [[1, 1, 3],
     [1, 2, 4],
     [1, 1, 2]]
Ainv = np.linalg.inv(A1)
Ainv

array([[ 0., -1.,  2.],
       [-2.,  1.,  1.],
       [ 1., -0., -1.]])

In [31]:
A2 = [[4, 6, 2],
     [3, 4, 1],
     [2, 8, 13]]

s = [9, 7, 2]

r = np.linalg.solve(A2, s)
r

array([ 3.00000000e+00, -5.00000000e-01, -1.98254112e-17])

In [32]:
A = np.array([
    [1, 2, 3],
    [4, 0, 1]
            ])

B = np.array([
    [1, 1, 0],
    [0, 1, 1],
    [1,0,1]
            ])

A.dot(B)

array([[4, 3, 5],
       [5, 4, 1]])

In [33]:
a = np.array([int(x) for x in "1321"]).reshape(4,1)
a

array([[1],
       [3],
       [2],
       [1]])

In [34]:
b = np.array([int(x) for x in "2456"]).reshape(1,4)
b

array([[2, 4, 5, 6]])

In [35]:
b.dot(a)

array([[30]])

In [36]:
a.dot(b)

array([[ 2,  4,  5,  6],
       [ 6, 12, 15, 18],
       [ 4,  8, 10, 12],
       [ 2,  4,  5,  6]])

In [37]:
A5 = np.array([
    [2 , -1],
    [0 , 3],
    [1 , 0]
            ])

B5 = np.array([
    [0, 1, 4,-1],
    [-2, 0,0, 2]
])
A5.dot(B5)

array([[ 2,  2,  8, -4],
       [-6,  0,  0,  6],
       [ 0,  1,  4, -1]])

# ejercicios de projeccion

Supongamos que los rayos del Sol entran en una dirección $ \hat {s} = \begin{bmatrix} 4/13 \\ -3/13 \\ -12/13  \\ \end{bmatrix}$

Construye la matriz, A , y aplícala a un punto, $r = \begin{bmatrix} 6 \\ 2 \\ 3  \\ \end{bmatrix}$, sobre un objeto en

nuestro espacio para encontrar la coordenas de $ r^{`}$

In [38]:
s = np.array([[ 4/13, -3/13, -12/13]])
s

array([[ 0.30769231, -0.23076923, -0.92307692]])

In [39]:
A = np.array([[ 1,0, -(s[0][0] / s[0][2]) ],
              [ 0,1, -(s[0][1] / s[0][2])]
             ])
A

array([[ 1.        ,  0.        ,  0.33333333],
       [ 0.        ,  1.        , -0.25      ]])

In [40]:
r = np.array([[6],[2],[3]])

In [41]:
coor_r = A.dot(r)

In [42]:
coor_r

array([[7.  ],
       [1.25]])

In [43]:
# ahora con un R de 3 x 4 aplicandole la misma transformacion

R = np.array([[5,-1,-3,7],[4,-4,1,-2],[9,3,0,12]])
R

array([[ 5, -1, -3,  7],
       [ 4, -4,  1, -2],
       [ 9,  3,  0, 12]])

In [44]:
Rp = A.dot(R)
Rp

array([[ 8.  ,  0.  , -3.  , 11.  ],
       [ 1.75, -4.75,  1.  , -5.  ]])

# Vectores Propios

Dada una matriz 
\\( \begin{bmatrix} a & b \\ c & d \end{bmatrix} \\)
 Recordemos que podemos calcular sus valores propios resolviendo el polinomio característico $\lambda^2 -(a+d)\lambda + (ad-bc) = 0 $. En este cuestionario practicarás el cálculo y la resolución del polinomio característico para hallar los valores propios de matrices sencillas.


Para la matriz \\( A = \begin{bmatrix} 1 & 0 \\ 0 & 2 \end{bmatrix} \\)

 ¿Cuál es el polinomio característico y las soluciones del polinomio característico?
 
$ \lambda^{2} -3\lambda + 2 = 0$ 

$\lambda_{1} = 1$   
$\lambda_{2} = 2$ 


Recordemos que para una matriz AA, los vectores propios de la matriz son vectores para los que la aplicación de la transformación de la matriz es la misma que la escala por alguna constante. 

Para $ A = \begin{bmatrix} 1 & 0 \\ 0 & 2 \end{bmatrix}$ 

 como en el caso anterior, seleccione todos los vectores propios de esta matriz.

- $  \begin{bmatrix} 1 \\  0 \end{bmatrix} $
- $  \begin{bmatrix} 0 \\  2 \end{bmatrix} $
- $  \begin{bmatrix} 0 \\  3 \end{bmatrix} $

In [45]:
A = np.array([[1,0],[0,2]])
A

array([[1, 0],
       [0, 2]])

In [46]:
A.dot(np.array([[1],[0]]))

array([[1],
       [0]])

In [47]:
A.dot(np.array([[0],[2]]))

array([[0],
       [4]])

In [48]:
A.dot(np.array([[0],[3]]))

array([[0],
       [6]])

In [49]:
A.dot(np.array([[1],[-1]]))

array([[ 1],
       [-2]])

In [50]:
A4 = np.array([[3,4],[0,5]])
A4

array([[3, 4],
       [0, 5]])

In [51]:
display(A4.dot(np.array([[0],[0]])))
display(A4.dot(np.array([[3],[0]])))
display(A4.dot(np.array([[2],[1]])))
display(A4.dot(np.array([[-1],[-(1/2)]])))

array([[0],
       [0]])

array([[9],
       [0]])

array([[10],
       [ 5]])

array([[-5. ],
       [-2.5]])

In [52]:
A6 = np.array([[3,4],[0,5]])
display(A6.dot(np.array([[3],[1]])))
display(A6.dot(np.array([[0],[1]])))
display(A6.dot(np.array([[3],[-1]])))
display(A6.dot(np.array([[3],[2]])))

array([[13],
       [ 5]])

array([[4],
       [5]])

array([[ 5],
       [-5]])

array([[17],
       [10]])

# eigenvectors


En este cuestionario diagonalizarás algunas matrices y lo aplicarás para simplificar los cálculos.

Dada la matriz $ T = \begin{bmatrix} 6 & -1 \\ 2 & 3\end{bmatrix} $ 

y cambio de matriz base $C = \begin{bmatrix} 1 & 1 \\ 1 & 2\end{bmatrix}$  


(cuyas columnas son los vectores propios de TT), calcular la matriz diagonal 
$D = C^{-1}TC$ 

In [53]:
T = np.array([[6,-1],
              [2,3]])
T

array([[ 6, -1],
       [ 2,  3]])

In [54]:
C = np.array([[1,1],
              [1,2]])
C

array([[1, 1],
       [1, 2]])

In [55]:
C_inv = np.linalg.inv(C)
C_inv

array([[ 2., -1.],
       [-1.,  1.]])

In [56]:
D = C_inv.dot(np.dot(T,C))
D

array([[5., 0.],
       [0., 4.]])

 Dada la matriz $T = \begin{bmatrix} 2 & 7 \\ 0 & -1 \end{bmatrix}$
 y cambio de matriz base $C = \begin{bmatrix} 7 & 1 \\ -3 & 0\end{bmatrix}$
 
 (cuyas columnas son los vectores propios de TT), calcular la matriz diagonal 
 $D = C^{-1}TC$

In [57]:
T = np.array([[2,7],
              [0,-1]])
C = np.array([[7,1],
              [-3,0]])
D = np.linalg.inv(C).dot(np.dot(T,C))
D

array([[-1.,  0.],
       [ 0.,  2.]])

In [58]:
T = np.array([[1,0],
              [2,-1]])
C = np.array([[1,0],
              [1,1]])
D = np.linalg.inv(C).dot(np.dot(T,C))
D

array([[ 1.,  0.],
       [ 0., -1.]])

Dada la matriz $ D = \begin{bmatrix} a & 0 \\ 0 & a\end{bmatrix}$  
, y cambio de matriz basex $C = \begin{bmatrix} 1 & 2 \\ 0 & 1\end{bmatrix}$  
con inversa $ C = \begin{bmatrix} 1 & -2 \\ 0 & 1\end{bmatrix}$,    
 calcula $T = CDC^{-1}$
 
 
 $ T = \begin{bmatrix} a & 0 \\ 0 & a\end{bmatrix}$

In [59]:
D = np.array([[10,0],
              [0,10]])
D

array([[10,  0],
       [ 0, 10]])

In [60]:
C = np.array([[1,2],
              [0,1]])
C

array([[1, 2],
       [0, 1]])

In [61]:
C_inv = np.linalg.inv(C)
C_inv

array([[ 1., -2.],
       [ 0.,  1.]])

In [62]:
CD = C.dot(D)
CD

array([[10, 20],
       [ 0, 10]])

In [63]:
CD.dot(C_inv)

array([[10.,  0.],
       [ 0., 10.]])


Given that $T = \begin{bmatrix} 6 & -1 \\ 2 & 3\end{bmatrix} = \begin{bmatrix} 1 & 1 \\ 1 & 2\end{bmatrix} \begin{bmatrix} 5 & 0 \\ 0 & 4\end{bmatrix} \begin{bmatrix} 2 & -1 \\ -1 & 1\end{bmatrix}$ , calculate $T^{3}$ 


In [64]:
np.dot(
    np.dot(
        np.array([[6,-1],[2,3]]),
        np.array([[6,-1],[2,3]])
            ),
    np.array([[6,-1],[2,3]])
)
       

array([[186, -61],
       [122,   3]])

In [65]:
a1 = 2
a2 = 0
b1 = 7
b2 = -1
C = np.array([[a1,b1],
              [a2,b2]])
np.dot(np.dot(C,C),C)

array([[ 8, 21],
       [ 0, -1]])

In [66]:
a1 = 1
a2 = 2
b1 = 0
b2 = -1
C = np.array([[a1,b1],
              [a2,b2]])
np.dot(np.dot(C,C),C)

array([[ 1,  0],
       [ 2, -1]])

In [3]:
# Eigenvalues
M = np.array([[1, 0, 0],
              [0, 2, 0],
              [0, 0, 3]])
vals, vecs = np.linalg.eig(M)
vals

array([1., 2., 3.])

In [4]:
# Eigenvectors - Note, the eigenvectors are the columns of the output.
M = np.array([[1, 0, 0],
              [0, 2, 0],
              [0, 0, 3]])
vals, vecs = np.linalg.eig(M)
vecs

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
M = np.array([[4, -5, 6],
              [7, -8, 6],
              [3/2, -1/2, -2]])
vals, vecs = np.linalg.eig(M)
vals , vecs

(array([ 1., -4., -3.]),
 array([[-0.6882472 , -0.66666667,  0.40824829],
        [-0.6882472 , -0.66666667, -0.40824829],
        [-0.22941573,  0.33333333, -0.81649658]]))

In [10]:
1/(9**0.5)

0.3333333333333333

In [11]:
1/9

0.1111111111111111

In [16]:
1 / (9**0.5)

3.0

In [14]:
(1/3) ** (-1)

3.0

In [21]:
np.linalg.eig(M)

(array([ 1., -4., -3.]),
 array([[-0.6882472 , -0.66666667,  0.40824829],
        [-0.6882472 , -0.66666667, -0.40824829],
        [-0.22941573,  0.33333333, -0.81649658]]))

In [25]:
vals.dot(vecs)

array([2.75298881, 1.        , 4.4907312 ])

-0.6666666666666666

In [ ]:
# Sympy

In [1]:
from sympy import *
a = symbols('a')
expression = a**2 - a - 1
# Define the symbol b
b = symbols('b')
# Use subs specifying to replace a with b + 1
expression.subs(a, b + 1)

-b + (b + 1)**2 - 2

In [2]:
27 // 4

6

In [3]:
a = 7
b = a * 2 - 8
a - b > 0

True