In [69]:
import numpy as np
from sympy import Matrix, symbols, Rational

Compute the projection matrix that allows us to project any vector 

$\mathbf{x}\in\mathbb{R}^3x∈ R^3$  
  onto the subspace spanned by the basis vector $\mathbf{b} = \begin{bmatrix}1\\2\\ 2\end{bmatrix}$  

Do the exercise using pen and paper. You can use the formula slide that comes with the corresponding lecture.

In [77]:
b = np.array([[1],[2],[2]])
b

array([[1],
       [2],
       [2]])

In [78]:
pi_b=b @ b.T 

In [79]:
d = (b.T @ b)
d

array([[9]])

In [80]:
Matrix(pi_b)

Matrix([
[1, 2, 2],
[2, 4, 4],
[2, 4, 4]])

9.0

In [74]:
b = np.array([[3],[0],[4]])
b

array([[3],
       [0],
       [4]])

In [75]:
pi_b=b @ b.T 
pi_b

array([[ 9,  0, 12],
       [ 0,  0,  0],
       [12,  0, 16]])

Given the projection matrix

$\displaystyle\frac{1}{25}\begin{bmatrix} 9 & 0 & 12\\ 0 & 0 & 0\\ 12 & 0 & 16 \end{bmatrix} $

project $\begin{bmatrix}1\\1\\1 \end{bmatrix}$ 

  onto the corresponding subspace, which is spanned by $\mathbf{b} = \begin{bmatrix} 3\\0\\4\end{bmatrix}$

In [38]:
ma = np.array([[9,0,12],[0,0,0],[12,0,16]]) * (1/25)
ma

array([[0.36, 0.  , 0.48],
       [0.  , 0.  , 0.  ],
       [0.48, 0.  , 0.64]])

In [45]:
proy = ma @ np.array([[1,1,1]]).T
proy

array([[0.84],
       [0.  ],
       [1.12]])

In [46]:
b = np.array([[3,0,4]]).T
b

array([[3],
       [0],
       [4]])

In [47]:
proy @ b.T @ b / (b.T @ b)

array([[0.84],
       [0.  ],
       [1.12]])

In [49]:
21/25,28/25

(0.84, 1.12)

Now, we compute the reconstruction error, i.e., the distance between the original data point and its projection onto a lower-dimensional subspace.

Assume our original data point is $\begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}$ 

  and its projection $\frac{1}{9} \begin{bmatrix} 5 \\ 10 \\ 10 \end{bmatrix}$ 
 . What is the reconstruction error?

Asumiendo que el producto interno es el producto escalar, solo necesitas calcular: $sqrt(<x-Pi_u(x), x-Pi_u(x)>)$, para obtener la respuesta.

In [57]:
x = np.array([[1,1,1]]).T
pi_x = np.array([[5,10,10]])

(array([[1],
        [1],
        [1]]),
 array([[0.55555556, 1.11111111, 1.11111111]]))

In [76]:
(pi_x -x).dot(x) 

array([[-0.22222222],
       [-0.22222222],
       [-0.22222222]])

In [78]:
(pi_x -x).T.dot(x)

array([[-1.33333333],
       [ 0.33333333],
       [ 0.33333333]])

In [80]:
(pi_x -x).dot(x).T   

array([[-0.22222222, -0.22222222, -0.22222222]])

In [86]:
((x-pi_x).dot(x).T @ (x-pi_x).dot(x) )

array([[0.14814815]])

In [114]:
((x-pi_x) @ (x-pi_x).T)

array([[0.22222222, 0.22222222, 0.22222222],
       [0.22222222, 0.22222222, 0.22222222],
       [0.22222222, 0.22222222, 0.22222222]])

In [111]:
pi_x.T

array([[0.55555556],
       [1.11111111],
       [1.11111111]])

In [112]:
pi_x

array([[0.55555556, 1.11111111, 1.11111111]])

The "hint" here is "...With a basis vector b of U...etc", so, we have to extract the basis vector b which is one of the components of the projection matrix. i.e : 1/9 [5, 10, 10] = 1/9 [5*1, 5*2, 5*2]. So, inside this matrix we have a scalar times vector, than : the basis vector b = [1, 2, 2]. Now we compute the distance x - b = [0, -1, -1]. 

||x - b|| = √(0)² + (-1)² + (-1)² = √2 = 1.414. we multiply by √λ = √1/9 = 1/3 then :

1.414 / 3 = 0.471 = reconstruction error.



La "pista" aquí es "...Con un vector base b de U...etc", por lo tanto, tenemos que extraer el vector base b que es uno de los componentes de la matriz de proyección. es decir : 1/9 [5, 10, 10] = 1/9 [5\*1, 5\*2, 5*2]. Por lo tanto, dentro de esta matriz tenemos un vector escalar veces, que : el vector base b = [1, 2, 2]. Ahora calculamos la distancia x - b = [0, -1, -1]. 

||x - b|| = √(0)² + (-1)² + (-1)² = √2 = 1.414. multiplicamos por √λ = √1/9 = 1/3 entonces :

1,414 / 3 = 0,471 = error de reconstrucción.



In [1]:
import numpy as np

For a vector $\mathbf{x} = \begin{bmatrix} 6 \\0\\ 0\end{bmatrix}$
  and the subspace UU spanned by the basis vectors  $\mathbf{b}_1=\begin{bmatrix} 1\\1\\1\end{bmatrix}$ 
  and $\mathbf{b}_2=\begin{bmatrix}0\\1\\2\end{bmatrix}$ 
 , which of the following statements are true?

You can use the formula slide that comes with the corresponding lecture.

In [48]:
# ejemplo del video

x = np.array([[2,1,1]]).T
b1 = np.array([[1,2,0]]).T
b2 = np.array([[1,1,0]]).T
B = np.hstack((b1,b2))

In [47]:
x,b1,b2

(array([[2],
        [1],
        [1]]),
 array([[1],
        [2],
        [0]]),
 array([[1],
        [1],
        [0]]))

In [49]:
B

array([[1, 1],
       [2, 1],
       [0, 0]])

In [50]:
B.T @ B

array([[5, 3],
       [3, 2]])

In [51]:
B.T @ x

array([[4],
       [3]])

In [52]:
np.linalg.inv(B.T @ B)

array([[ 2., -3.],
       [-3.,  5.]])

In [54]:
l=np.linalg.inv(B.T @ B) @ (B.T @ x)
l

array([[-1.],
       [ 3.]])

In [55]:
pi_u = l[0] * b1 + l[1]*b2
pi_u

array([[2.],
       [1.],
       [0.]])

In [107]:
x = np.array([[6,0,0]]).T
b1 = np.array([[1,1,1]]).T
b2 = np.array([[0,1,2]]).T
B = np.hstack((b1,b2))
x,b1,b2,B

(array([[6],
        [0],
        [0]]),
 array([[1],
        [1],
        [1]]),
 array([[0],
        [1],
        [2]]),
 array([[1, 0],
        [1, 1],
        [1, 2]]))

In [108]:
B.T @ B

array([[3, 3],
       [3, 5]])

In [109]:
np.linalg.inv(B.T @ B)

array([[ 0.83333333, -0.5       ],
       [-0.5       ,  0.5       ]])

In [110]:
l=np.linalg.inv(B.T @ B) @ (B.T @ x)
l

array([[ 5.],
       [-3.]])

In [111]:
pi_u = l[0] * b1 + l[1]*b2
pi_u

array([[ 5.],
       [ 2.],
       [-1.]])

In [93]:
pi_B = (B @ B.T)
pi_B

array([[1, 1, 1],
       [1, 2, 3],
       [1, 3, 5]])

In [116]:
matrix_proj = B @ np.linalg.inv(B.T @ B) @ B.T 
matrix_proj * 6

array([[ 5.,  2., -1.],
       [ 2.,  2.,  2.],
       [-1.,  2.,  5.]])

In [117]:
x = np.array([[3,2,2]]).T
b1 = np.array([[1,0,0]]).T
b2 = np.array([[0,1,1]]).T
B = np.hstack((b1,b2))
l=np.linalg.inv(B.T @ B) @ (B.T @ x)
pi_u = l[0] * b1 + l[1]*b2
pi_u

array([[3.],
       [2.],
       [2.]])

In [104]:
x = np.array([[12,0,0]]).T
b1 = np.array([[1,1,1]]).T
b2 = np.array([[0,1,2]]).T
B = np.hstack((b1,b2))
pi_B= B @ B.T

pi_B

array([[1, 1, 1],
       [1, 2, 3],
       [1, 3, 5]])

In [105]:
pi_B / (B.T @ B)

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [106]:
l=np.linalg.inv(B.T @ B) @ (B.T @ x)
pi_u = l[0] * b1 + l[1]*b2
pi_u

array([[10.],
       [ 4.],
       [-2.]])