En este cuestionario practicarás el cálculo de la regla de la cadena multivariante para varias funciones. 


Para las siguientes funciones, calcula la expresión $\frac{df}{dt} = \frac{\partial f}{\partial \mathbf{x}} \frac{d\mathbf{x}}{dt}$
 en forma de matriz, donde
 
- $\mathbf{x} = (x_1, x_2)$  

- $f(\mathbf{x}) = f(x_1, x_2) =x_1^2x_2^2 + x_1x_2$

- $ x_{1}(t)=1-t^{2} $ 
- $ x_{2}(t)=1+t^{2} $ 

In [33]:
from sympy import symbols, sin, cos, exp, pi, diff , sqrt
from sympy import Rational
from sympy.matrices import Matrix

In [34]:
x,t ,x1,x2= symbols("x,t,x1,x2")

In [28]:
x1

x1

In [35]:
fx = x1**2*x2**2+x1*x2
fx

x1**2*x2**2 + x1*x2

In [36]:
diff(fx,x1)

2*x1*x2**2 + x2

In [38]:
df_X = Matrix([[diff(fx,x1),
                diff(fx,x2)
               ]])
df_X

Matrix([[2*x1*x2**2 + x2, 2*x1**2*x2 + x1]])

In [39]:
x1 = 1 - t**2
x2 = 1 + t**2 
display(x1)
display(x2)

1 - t**2

t**2 + 1

In [40]:
dX_t = Matrix([[diff(x1,t)],[diff(x2,t)]])
dX_t

Matrix([
[-2*t],
[ 2*t]])

In [43]:
df_X.dot(dX_t) 

-2*t*(2*x1*x2**2 + x2) + 2*t*(2*x1**2*x2 + x1)

In [41]:
df_X * dX_t

Matrix([[-2*t*(2*x1*x2**2 + x2) + 2*t*(2*x1**2*x2 + x1)]])

In [44]:
t,x1,x2,x3= symbols("t,x1,x2,x3")

In [46]:
f_X = x1**3*cos(x2)*exp(x3)
f_X

x1**3*exp(x3)*cos(x2)

In [64]:
dF_dX = Matrix([[diff(f_X,x1),diff(f_X,x2),diff(f_X,x3)]])
dF_dX

Matrix([[3*x1**2*exp(x3)*cos(x2), -x1**3*exp(x3)*sin(x2), x1**3*exp(x3)*cos(x2)]])

In [66]:
x1 = 2*t
x2 = 1- t**2
x3 = exp(t)
display(x1)
display(x2)
display(x3)

2*t

1 - t**2

exp(t)

In [67]:
dX_dt = Matrix([[diff(x1,t)],[diff(x2,t)],[diff(x3,t)]])
dX_dt

Matrix([
[     2],
[  -2*t],
[exp(t)]])

In [93]:
t,x1,x2,u1,u2= symbols("t,x1,x2,u1,u2")

In [94]:
f_X = x1**2 - x2**2
f_X

x1**2 - x2**2

In [95]:
df_dX = Matrix([[diff(f_X,x1),diff(f_X,x2)]])
df_dX

Matrix([[2*x1, -2*x2]])

In [96]:
x1 = 2*u1 + 3*u2
x2 = 2*u1 - 3*u2

In [97]:
x1

2*u1 + 3*u2

In [98]:
x2

2*u1 - 3*u2

In [99]:
dX_dU = Matrix([[diff(x1,u1),diff(x1,u2)],
                [diff(x2,u1),diff(x2,u2)]])
dX_dU

Matrix([
[2,  3],
[2, -3]])

In [100]:
u1 = cos(Rational(1,2)*t)
u1

cos(t/2)

In [101]:
u2 = sin(2*t)
u2

sin(2*t)

In [102]:
dU_dt = Matrix([[diff(u1,t)],[diff(u2,t)]])
dU_dt

Matrix([
[-sin(t/2)/2],
[ 2*cos(2*t)]])

In [107]:
x1,x2,x3,u1,u2 = symbols("x1,x2,x3,u1,u2")

In [108]:
f_x = sin(x1)*cos(x2)*exp(x3)
f_x

exp(x3)*sin(x1)*cos(x2)

In [110]:
dF_dX = Matrix([[diff(f_x,x1),diff(f_x,x2),diff(f_x,x3)]])
dF_dX

Matrix([[exp(x3)*cos(x1)*cos(x2), -exp(x3)*sin(x1)*sin(x2), exp(x3)*sin(x1)*cos(x2)]])

In [112]:
x1 = sin(u1) + cos(u2)
x2 = -sin(u2) + cos(u1)
x3 = exp(u1+u2)
display(x1)
display(x2)
display(x3)

sin(u1) + cos(u2)

-sin(u2) + cos(u1)

exp(u1 + u2)

In [114]:
dX_dU = Matrix([[diff(x1,u1),diff(x1,u2)],
                [diff(x2,u1),diff(x2,u2)],
                [diff(x3,u1),diff(x3,u2)]])
dX_dU

Matrix([
[     cos(u1),     -sin(u2)],
[    -sin(u1),     -cos(u2)],
[exp(u1 + u2), exp(u1 + u2)]])

In [115]:
u1 = 1 + Rational(1,2)*t
u2 = 1 - Rational(1,2)*t
display(u1)
display(u2)

t/2 + 1

1 - t/2

In [116]:
dU_dt = Matrix([[diff(u1,t)],[diff(u2,t)]])
dU_dt

Matrix([
[ 1/2],
[-1/2]])

In [120]:
x1,x2,x3,u1,u2,t = symbols("x1,x2,x3,u1,u2,t")

In [121]:
f_x = sin(x2)*cos(x1)
f_x

sin(x2)*cos(x1)

In [124]:
x1 = u1**2*2 +  3 *u2**2 - u2
x2 = 2*u1 - 5 *u2**3
display(x1)
display(x2)

2*u1**2 + 3*u2**2 - u2

2*u1 - 5*u2**3

In [125]:
dX_dU = Matrix([[diff(x1,u1),diff(x1,u2)],
                [diff(x2,u1),diff(x2,u2)],
                ])
dX_dU

Matrix([
[4*u1,  6*u2 - 1],
[   2, -15*u2**2]])

In [128]:
u1 = exp(Rational(1,2)*t)
u2 = exp(-t*2)
display(u1)
display(u2)

exp(t/2)

exp(-2*t)

In [129]:
dU_dt = Matrix([[diff(u1,t)],[diff(u2,t)]])
dU_dt

Matrix([
[  exp(t/2)/2],
[-2*exp(-2*t)]])

In [130]:
import numpy as np

In [132]:
w= np.array([[-2,4,-1],
             [6,0,-3]])
w

array([[-2,  4, -1],
       [ 6,  0, -3]])

In [133]:
x=np.array([[0.3,.4,.1]]).T
x

array([[0.3],
       [0.4],
       [0.1]])

In [140]:
np.tanh(w.dot(x) + np.array([[0.1],[-2.5]]))

array([[ 0.76159416],
       [-0.76159416]])

In [142]:
# First we set the state of the network
σ = np.tanh
w1 = 1.3
b1 = -0.1

# Then we define the neuron activation.
def a1(a0) :
  z = w1 * a0 + b1
  return σ(z)

# Experiment with different values of x below.
x = 0
(a1(x)-1)**2


1.209269698402472

In [145]:
sigma = np.tanh

# Let's use a random initial weight and bias.
W = np.array([[-0.94529712, -0.2667356 , -0.91219181],
              [ 2.05529992,  1.21797092,  0.22914497]])
b = np.array([ 0.61273249,  1.6422662 ])

# define our feed forward function
def a1 (a0) :
  # Notice the next line is almost the same as previously,
  # except we are using matrix multiplication rather than scalar multiplication
  # hence the '@' operator, and not the '*' operator.
  z = W @ a0 + b
  # Everything else is the same though,
  return sigma(z)

# Next, if a training example is,
x = np.array([0.7, 0.6, 0.2])
y = np.array([0.9, 0.6])

# Then the cost function is,
d = a1(x) - y # Vector difference between observed and expected activation
C = d @ d # Absolute value squared of the difference.
round(C,1)

1.8