In [1]:
import numpy as np


Compute the length of

$\mathbf{x} = \begin{bmatrix}1\\-1\\3\end{bmatrix}$

using the inner product defined

$\langle \mathbf{a}, \mathbf{b}\rangle = \mathbf{a}^T \begin{bmatrix} 2 & 1 & 0\\1 & 2 & -1\\0 & -1 & 2\end{bmatrix}\mathbf{b}$

In [2]:
x = np.array([[1,-1,3]])
x

array([[ 1, -1,  3]])

In [3]:
y = np.array([[2,1,0],[1,2,-1],[0,-1,2]])
y

array([[ 2,  1,  0],
       [ 1,  2, -1],
       [ 0, -1,  2]])

In [16]:
a = y.dot(x.T)
a

array([[ 1],
       [-4],
       [ 7]])

In [19]:
ab = (x.dot(a))
ab

array([[26]])


Compute the squared distance between

$\mathbf{x} = \begin{bmatrix}\frac{1}{2} \\-1 \\-\frac{1}{2}\end{bmatrix}$
 

and 

$\mathbf{y} = \begin{bmatrix}0\\1\\0\end{bmatrix}$

using the inner product defined as

$\langle \mathbf{a}, \mathbf{b}\rangle = \mathbf{a}^T \begin{bmatrix} 2 & 1 & 0\\1 & 2 & -1\\0 & -1 & 2\end{bmatrix}\mathbf{b}$

In [86]:
y = np.array([[0,1,0]])
x = np.array([[1/2,-1,-1/2]])
A = np.array([[2,1,0],[1,2,-1],[0,-1,2]])
x,y,A

(array([[ 0.5, -1. , -0.5]]),
 array([[0, 1, 0]]),
 array([[ 2,  1,  0],
        [ 1,  2, -1],
        [ 0, -1,  2]]))

In [87]:
(y-x).dot(A).dot((y-x).T)

array([[5.]])

Compute the length of $\mathbf{x} = \begin{bmatrix}-1\\1\end{bmatrix}$

using the inner product defined by 

$\langle\mathbf{a}, \mathbf{b}\rangle = \mathbf{a}^T\frac{1}{2}\begin{bmatrix}5 & -1\\ -1 & 5\end{bmatrix}\mathbf{b}$

In [89]:
x = np.array([[-1],[1]])
x

array([[-1],
       [ 1]])

In [90]:
A = np.array([[5,-1],[-1,5]])
A

array([[ 5, -1],
       [-1,  5]])

In [91]:
x.T.dot(A*(1/2)).dot(x)

array([[6.]])

Compute the distance (not squared) between

$\mathbf{x} = \begin{bmatrix}4 \\2 \\1\end{bmatrix}$

and

$\mathbf{y} = \begin{bmatrix}0\\1\\0\end{bmatrix}$
 

using the inner product defined as

$\langle \mathbf{a}, \mathbf{b}\rangle = \mathbf{a}^T \begin{bmatrix} 2 & 1 & 0\\1 & 2 & -1\\0 & -1 & 2\end{bmatrix}\mathbf{b}$

In [92]:
x = np.array([[4],[2],[1]])
y = np.array([[0],[1],[0]])
A = np.array([[2,1,0],[1,2,-1],[0,-1,2]])
x,y,A

(array([[4],
        [2],
        [1]]),
 array([[0],
        [1],
        [0]]),
 array([[ 2,  1,  0],
        [ 1,  2, -1],
        [ 0, -1,  2]]))

In [94]:
np.sqrt((x-y).T.dot(A).dot((x-y)))

array([[6.4807407]])

In [216]:
x = np.array([[1],[1]])
y = np.array([[-1],[1]])
A = np.array([[2,0],[0,1]])
x,y,A

(array([[1],
        [1]]),
 array([[-1],
        [ 1]]),
 array([[2, 0],
        [0, 1]]))

In [217]:
x.T.dot(A).dot(y)

array([[-1]])

In [222]:
np.rad2deg(np.arccos(x.T.dot(A).dot(y)))

array([[180.]])

In [211]:
np.radians(0)

0.0

In [212]:
np.deg2rad(0.0)

0.0

In [213]:
np.radians(90)

1.5707963267948966

In [141]:
np.rad2deg(np.pi)

180.0

In [143]:
x.T.dot(y)

array([[0]])

Compute the angle between $\mathbf{x} = \begin{bmatrix}1\\1\end{bmatrix}$  
and   
$\mathbf{y} = \begin{bmatrix}-1\\1\end{bmatrix}$

using the inner product defined by

$\langle \mathbf{x},\mathbf{y}\rangle = \mathbf{x}^T\begin{bmatrix}2& -1 \\ -1 &  4\end{bmatrix}\mathbf{y}$

In [223]:
x = np.array([[1],[1]])
y = np.array([[-1],[1]])
A = np.array([[2,-1],[-1,4]])
x,y,A

(array([[1],
        [1]]),
 array([[-1],
        [ 1]]),
 array([[ 2, -1],
        [-1,  4]]))

In [226]:
x.T.dot(A).dot(y)

array([[2]])

In [234]:
np.sqrt((x.T @ A @ x)*(y.T @ A @ y)) 

array([[5.65685425]])

In [231]:
cosW = (x.T.dot(A) @ y) / np.sqrt((x.T @ A @ x)*(y.T @ A @ y))

In [232]:
cosW

array([[0.35355339]])

In [233]:
np.arccos(cosW)

array([[1.2094292]])

Compute the angle between $\mathbf{x} = \begin{bmatrix}0\\-1\end{bmatrix}$
and $\mathbf{y} = \begin{bmatrix}1\\1\end{bmatrix}$
using the inner product defined by

$\langle \mathbf{x},\mathbf{y}\rangle = \mathbf{x}^T\begin{bmatrix}1 & -\tfrac{1}{2}\\ -\tfrac{1}{2} & 5\end{bmatrix}\mathbf{y}$
To aid in computing this angle and the next ones in this quiz, let's write an expression in Python for the angle between two vectors using a non-standard inner product.

Remember $\cos{\alpha} = \frac{\langle x,y\rangle}{\|x\|\cdot\|y\|} = \frac{\langle x,y\rangle}{\sqrt{\langle x,x\rangle}\cdot\sqrt{\langle y,y\rangle}}$
 

Complete the expressions for norm_x and norm_y and then run the code. You might find the NumPy function np.sqrt useful.

In [239]:
def find_angle(A, x, y):
    """Compute the angle"""
    inner_prod = x.T @ A @ y
    # Fill in the expression for norm_x and norm_y below
    norm_x = x.T @ A @ x
    norm_y = y.T @ A @ y
    alpha = inner_prod/ np.sqrt((norm_x*norm_y))
    angle = np.arccos(alpha)
    return np.round(angle,2) 

In [240]:
# the matrix A defines the inner product
A = np.array([[1, -1/2],[-1/2,5]])
x = np.array([0,-1])
y = np.array([1,1])

In [241]:
find_angle(A, x, y)

2.69

In [242]:
# the matrix A defines the inner product
A = np.array([[2, 1],[1,4]])
x = np.array([2,2])
y = np.array([-2,-2])
display(x)
display(y)
display(A)
find_angle(A, x, y)

array([2, 2])

array([-2, -2])

array([[2, 1],
       [1, 4]])

3.14

In [243]:
# Fill in the arrays and use the function `find_angle` defined for you to aid in your calculation
A = np.array([ [1,0],[0,5]])
x = np.array([[1],[1]])
y = np.array([[1],[-1]])

find_angle(A, x, y)

array([[2.3]])